--------------------------------------------------------------------------------
-- FILE   : echo_server-api.ads
-- SUBJECT: Specification of a package that defines the Echo_Server API
-- AUTHOR : (C) Copyright 2024 by Vermont State University
--
-- All the subprograms in this package are task safe.
--
-- THIS FILE WAS GENERATED BY Merc. DO NOT EDIT UNLESS NECESSARY!!
--------------------------------------------------------------------------------
pragma SPARK_Mode(On);

with CubedOS.Lib;
with Message_Manager;  use Message_Manager;
with System;
with Name_Resolver;
with CubedOS.Lib.XDR;
use  CubedOS.Lib.XDR;

package Echo_Server.API is

   type Message_Type is
      (Ping_Reply,
      Ping_Request);

   type Status_Type is
      (Success, 
      Failure);

   function Ping_Request_Encode
      (Sender_Address : in Message_Address;
      Request_ID : in Request_ID_Type;
      -- TODO
      Priority : in System.Priority := System.Default_Priority) return Message_Record
   with
      Global => null;

   function Is_Ping_Request(Message : in Message_Record) return Boolean is
      (Message.Receiver_Address =
         Name_Resolver.Echo_Server and Message.Message_ID = Message_Type'Pos(Ping_Request));


   function Ping_Reply_Encode
      (Receiver_Address : in Message_Address;
      Request_ID : in Request_ID_Type;
      Status : in Status_Type;
      Priority : in System.Priority := System.Default_Priority) return Message_Record
   with
      Global => null;

   function Is_Ping_Reply(Message : in Message_Record) return Boolean is
      (Message.Sender_Address =
         Name_Resolver.Echo_Server and Message.Message_ID = Message_Type'Pos(Ping_Reply));

   procedure Ping_Reply_Decode
      (Message : in  Message_Record;
      Status : out Status_Type;
      Decode_Status : out Message_Status_Type)
   with
      Global => null,
      Pre => Is_Ping_Reply(Message),
      Depends => ((Status, Decode_Status) => Message);



end Echo_Server.API;
