--------------------------------------------------------------------------------
-- FILE   : echo_server-api.adb
-- SUBJECT: Body of a package that implements the Echo_Server API
-- AUTHOR : (C) Copyright 2024 by Vermont State University
--
-- All the subprograms in this package are task safe.
--
-- THIS FILE WAS GENERATED BY Merc. DO NOT EDIT UNLESS NECESSARY!!
--------------------------------------------------------------------------------
pragma SPARK_Mode(On);

with CubedOS.Lib;
use  CubedOS.Lib;

package body Echo_Server.API is

   function Ping_Request_Encode
      (Sender_Address : in Message_Address;
      Request_ID : in Request_ID_Type;
      -- TODO
      Priority : in System.Priority := System.Default_Priority) return Message_Record
   is
      Message : Message_Record;
      Position : Data_Index_Type;
   begin
      Message := Make_Empty_Message(
         Sender_Address   => Sender_Address,
         Receiver_Address => Name_Resolver.Echo_Server,
         Request_ID   => Request_ID,
         Message_ID => Message_Type'Pos(Ping_Request),
         Priority   => Priority);
      Position := 0;
      -- TODO
      Message.Size := Position;
      return Message;
   end Ping_Request_Encode;


   function Ping_Reply_Encode
      (Receiver_Address : in Message_Address;
      Request_ID : in Request_ID_Type;
      Status : in Status_Type;
      Priority : in System.Priority := System.Default_Priority) return Message_Record
   is
      Message : Message_Record := Make_Empty_Message(
         Sender_Address   => Name_Resolver.Echo_Server,
         Receiver_Address => Receiver_Address,
         Request_ID   => Request_ID,
         Message_ID => Message_Type'Pos(Ping_Reply),
         Priority   => Priority);
      Position : Data_Index_Type;
      Last : Data_Index_Type;
   begin
      Position := 0;
      XDR.Encode(XDR.XDR_Unsigned(Status_Type'Pos(Status)), Message.Payload, Position, Last);
      Position := Last + 1;
      Message.Size := Position;
      return Message;
   end Ping_Reply_Encode;

   procedure Ping_Reply_Decode
      (Message : in  Message_Record;
      Status : out Status_Type;
      Decode_Status : out Message_Status_Type)
   is
      Position : Data_Index_Type;
      Raw_Status : XDR.XDR_Unsigned;
      Last : Data_Index_Type;
   begin
      pragma Warnings
         (Off, "unused assignment to ""Last""", Reason => "The last value of Last is not needed");
      Decode_Status := Success;
      Status := Status_Type'First;
      Position := 0;
      if Decode_Status = Success then
         XDR.Decode(Message.Payload, Position, Raw_Status, Last);
         if Raw_Status in Status_Type'Pos(Status_Type'First) .. Status_Type'Pos(Status_Type'Last) then
            Status := Status_Type'Val(Raw_Status);
         else
            Decode_Status := Malformed;
            Status := Status_Type'First;
         end if;
      end if;
   end Ping_Reply_Decode;


end Echo_Server.API;
