--------------------------------------------------------------------------------
-- FILE   : %FILENAME%-api.adb
-- SUBJECT: Body of a package that implements the %MODULENAME% API
-- AUTHOR : (C) Copyright 2024 by Vermont State University
--
-- All the subprograms in this package are task safe.
--
-- THIS FILE WAS GENERATED BY Merc. DO NOT EDIT UNLESS NECESSARY!!
--------------------------------------------------------------------------------
pragma SPARK_Mode(On);

with CubedOS.Lib;
with CubedOS.Log_Server.API;
use  CubedOS.Lib;

package body %MODULENAME%.API is

   %BULK%

end %MODULENAME%.API;
