--------------------------------------------------------------------------------
-- FILE   : %FILENAME%-api.ads
-- SUBJECT: Specification of a package that defines the %MODULENAME% API
-- AUTHOR : (C) Copyright 2024 by Vermont State University
--
-- All the subprograms in this package are task safe.
--
-- THIS FILE WAS GENERATED BY Merc. DO NOT EDIT UNLESS NECESSARY!!
--------------------------------------------------------------------------------
pragma SPARK_Mode(On);

with CubedOS.Lib;
with Message_Manager;  use Message_Manager;
with System;
with Name_Resolver;
with CubedOS.Lib.XDR;
use  CubedOS.Lib.XDR;

package %MODULENAME%.API is

   %BULK%

end %MODULENAME%.API;
