--------------------------------------------------------------------------------
-- FILE   : camera-api.adb
-- SUBJECT: Body of a package that implements the Camera API
-- AUTHOR : (C) Copyright 2024 by Vermont State University
--
-- All the subprograms in this package are task safe.
--
-- THIS FILE WAS GENERATED BY Merc. DO NOT EDIT UNLESS NECESSARY!!
--------------------------------------------------------------------------------
pragma SPARK_Mode(On);

with CubedOS.Lib;
use  CubedOS.Lib;

package body Camera.API is

   function Take_Image_Request_Encode
      (Sender_Address : in Message_Address;
      Request_ID : in Request_ID_Type;
      -- TODO
      Priority : in System.Priority := System.Default_Priority) return Message_Record
   is
      Message : Message_Record;
      Position : Data_Index_Type;
   begin
      Message := Make_Empty_Message(
         Sender_Address   => Sender_Address,
         Receiver_Address => Name_Resolver.Camera,
         Request_ID   => Request_ID,
         Message_ID => Message_Type'Pos(Take_Image_Request),
         Priority   => Priority);
      Position := 0;
      -- TODO
      Message.Size := Position;
      return Message;
   end Take_Image_Request_Encode;


   function Take_Image_Reply_Encode
      (Receiver_Address : in Message_Address;
      Request_ID : in Request_ID_Type;
      File_Name : in String;
      Priority : in System.Priority := System.Default_Priority) return Message_Record
   is
      Message : Message_Record := Make_Empty_Message(
         Sender_Address   => Name_Resolver.Camera,
         Receiver_Address => Receiver_Address,
         Request_ID   => Request_ID,
         Message_ID => Message_Type'Pos(Take_Image_Reply),
         Priority   => Priority);
      Position : Data_Index_Type;
      Last : Data_Index_Type;
   begin
      Position := 0;
      XDR.Encode(XDR.XDR_Unsigned(File_Name'Length), Message.Payload, Position, Last);
      Position := Last + 1;
      XDR.Encode(File_Name, Message.Payload, Position, Last);
      Position := Last + 1;
      Message.Size := Position;
      return Message;
   end Take_Image_Reply_Encode;

   procedure Take_Image_Reply_Decode
      (Message : in  Message_Record;
      File_Name : out String;
      File_Name_Size : out Natural;
      Decode_Status : out Message_Status_Type)
   is
      Position : Data_Index_Type;
      Raw_File_Name_Size : XDR.XDR_Unsigned;
      Last : Data_Index_Type;
   begin
      pragma Warnings
         (Off, "unused assignment to ""Last""", Reason => "The last value of Last is not needed");
      Decode_Status := Success;
      File_Name := [others => ' '];
      Position := 0;
      XDR.Decode(Message.Payload, Position, Raw_File_Name_Size, Last);
      Position := Last + 1;
      if Raw_File_Name_Size in XDR.XDR_Unsigned(Natural'First) .. XDR.XDR_Unsigned(Natural'Last) then
         File_Name_Size := Natural(Raw_File_Name_Size);
      else
         File_Name_Size := 0;
      end if;
      if File_Name_Size < 1 then
         XDR.Decode(Message.Payload,
                    Position,
                    File_Name(File_Name'First .. File_Name'First + (File_Name_Size - 1)), Last);
      end if;
   end Take_Image_Reply_Decode;


end Camera.API;
