--------------------------------------------------------------------------------
-- FILE   : cubedos-m0001-api.ads
-- SUBJECT: Specification of a package that defines the CubedOS.m0001 API
-- AUTHOR : (C) Copyright 2024 by Vermont State University
--
-- All the subprograms in this package are task safe.
--
-- THIS FILE WAS GENERATED BY Merc. DO NOT EDIT UNLESS NECESSARY!!
--------------------------------------------------------------------------------
pragma SPARK_Mode(On);

with CubedOS.Lib;
with Message_Manager;  use Message_Manager;
with System;
with Name_Resolver;
with CubedOS.Lib.XDR;
use  CubedOS.Lib.XDR;

package CubedOS.m0001.API is

   type Message_Type is
      (Trivial_Reply,
      Trivial_Request);

   function Trivial_Request_Encode
      (Sender_Address : in Message_Address;
      Request_ID : in Request_ID_Type;
      M1 : in Integer;
      Priority : in System.Priority := System.Default_Priority) return Message_Record
   with
      Global => null;

   function Is_Trivial_Request(Message : in Message_Record) return Boolean is
      (Message.Receiver_Address =
         Name_Resolver.m0001 and Message.Message_ID = Message_Type'Pos(Trivial_Request));

   procedure Trivial_Request_Decode
      (Message : in  Message_Record;
      M1 : out Integer;
      Decode_Status : out Message_Status_Type)
   with
      Global => null,
      Pre => Is_Trivial_Request(Message),
      Depends => ((M1, Decode_Status) => Message);


   function Trivial_Reply_Encode
      (Receiver_Address : in Message_Address;
      Request_ID : in Request_ID_Type;
      M1 : in Integer;
      Priority : in System.Priority := System.Default_Priority) return Message_Record
   with
      Global => null;

   function Is_Trivial_Reply(Message : in Message_Record) return Boolean is
      (Message.Sender_Address =
         Name_Resolver.m0001 and Message.Message_ID = Message_Type'Pos(Trivial_Reply));

   procedure Trivial_Reply_Decode
      (Message : in  Message_Record;
      M1 : out Integer;
      Decode_Status : out Message_Status_Type)
   with
      Global => null,
      Pre => Is_Trivial_Reply(Message),
      Depends => ((M1, Decode_Status) => Message);



end CubedOS.m0001.API;
